/**
 * Title, description and canonical construction, with build-time enforcement.
 *
 * The length checks are the point. A meta description silently truncated at
 * 158 characters, or a title that never got its brand suffix, is invisible in
 * review and expensive in a SERP. Warning at build time makes the whole set
 * auditable in one `bun run build` rather than one page at a time.
 */

import { SITE_URL, COMPANY } from '../data/company';

const SUFFIX = ` | ${COMPANY.shortName}`;

/** Google truncates around 60 characters; under 30 usually means it's a stub. */
const TITLE_MIN = 30;
const TITLE_MAX = 65;

/** The window in which a description is rendered whole on desktop and mobile. */
const DESC_MIN = 120;
const DESC_MAX = 158;

function warn(kind: string, value: string, min: number, max: number, path: string) {
  if (import.meta.env.PROD) {
    console.warn(
      `[seo] ${path}: ${kind} is ${value.length} chars (want ${min}-${max})\n      "${value}"`,
    );
  }
}

/**
 * Appends the brand suffix unless the title already carries it, and unless
 * doing so would push a long title past the truncation point.
 */
export function buildTitle(
  title: string | undefined,
  path = '',
  /**
   * Waives the lower bound. The 30-character floor is a heuristic for spotting
   * stub titles, and a few pages are legitimately short — "Terms of use —
   * Elucidsoft LLC" is a complete, accurate title at 29 characters. Padding it
   * to clear an arbitrary threshold would add exactly the filler this site is
   * written to avoid. The upper bound still applies, because that one is a
   * real truncation point rather than a guess.
   */
  allowShort = false,
): string {
  if (!title) return `${COMPANY.shortName}: Software Company`;
  const full = title.includes(COMPANY.shortName) ? title : `${title}${SUFFIX}`;
  const tooShort = !allowShort && full.length < TITLE_MIN;
  if (tooShort || full.length > TITLE_MAX) {
    warn('title', full, allowShort ? 0 : TITLE_MIN, TITLE_MAX, path);
  }
  return full;
}

export function buildDescription(description: string, path = ''): string {
  if (description.length < DESC_MIN || description.length > DESC_MAX) {
    warn('description', description, DESC_MIN, DESC_MAX, path);
  }
  return description;
}

/**
 * Absolute canonical with a normalised trailing slash.
 *
 * The site runs `trailingSlash: 'always'`, so a canonical written without one
 * points at a URL that redirects — which is a self-inflicted crawl cost on
 * every page. File extensions (.txt, .xml, .md) are left alone.
 */
export function buildCanonical(pathname: string): string {
  let p = pathname || '/';
  if (!p.startsWith('/')) p = `/${p}`;
  const hasExtension = /\.[a-z0-9]+$/i.test(p);
  if (!hasExtension && !p.endsWith('/')) p = `${p}/`;
  return new URL(p, SITE_URL).href;
}

/** Absolute URL for any site-relative asset path. */
export function absolute(path: string): string {
  return new URL(path, SITE_URL).href;
}

/**
 * Resolves the OG card for a route.
 *
 * Cards are generated by scripts/og-images.mjs, which owns the same list of
 * names. A route with no card of its own falls back to the default rather than
 * pointing at a file that does not exist — a 404 on an og:image is worse than
 * a generic preview, because the platform renders nothing at all.
 */
const OG_ROUTES: Record<string, string> = {
  '/': 'default',
  '/portfolio/': 'portfolio',
  '/open-source/': 'open-source',
  '/about/': 'about',
  '/contact/': 'contact',
  '/facts/': 'facts',
  '/news/': 'news',
};

export function ogCardFor(pathname: string): string {
  const path = pathname.endsWith('/') ? pathname : `${pathname}/`;

  const exact = OG_ROUTES[path];
  if (exact) return `/og/${exact}.png`;

  const product = path.match(/^\/portfolio\/([a-z0-9-]+)\/$/);
  if (product) return `/og/${product[1]}.png`;

  // News articles without their own hero share the news card.
  if (path.startsWith('/news/')) return '/og/news.png';

  return '/og/default.png';
}

export interface Breadcrumb {
  name: string;
  href: string;
}

export function breadcrumbSchema(trail: Breadcrumb[]) {
  return {
    '@type': 'BreadcrumbList',
    itemListElement: trail.map((crumb, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: crumb.name,
      item: buildCanonical(crumb.href),
    })),
  };
}
